Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
function Initialize-Module([string]$Root){
 $script:ModuleRoot=(Resolve-Path -LiteralPath $Root).Path;$script:ConfigRoot=Join-Path $ModuleRoot 'config\runtime';$script:DataRoot=Join-Path $ModuleRoot 'data';$script:LogRoot=Join-Path $ModuleRoot 'logs';$script:StateRoot=Join-Path $ModuleRoot 'state';$script:TempRoot=Join-Path $ModuleRoot 'temp'
 New-Item -ItemType Directory -Path $ConfigRoot,$DataRoot,$LogRoot,$StateRoot,$TempRoot -Force|Out-Null
 $keep=@{};foreach($name in @('SystemRoot','windir','ComSpec','SystemDrive','PATHEXT','OS','COMPUTERNAME','PROCESSOR_ARCHITECTURE','PROCESSOR_IDENTIFIER','NUMBER_OF_PROCESSORS')){$value=[Environment]::GetEnvironmentVariable($name,'Process');if($null -ne $value){$keep[$name]=$value}};Get-ChildItem Env:|ForEach-Object{[Environment]::SetEnvironmentVariable($_.Name,$null,'Process')};foreach($item in $keep.GetEnumerator()){[Environment]::SetEnvironmentVariable($item.Key,$item.Value,'Process')}
 $env:PATH="$env:SystemRoot\System32;$env:SystemRoot;$env:SystemRoot\System32\Wbem";$env:HOME=Join-Path $DataRoot 'profile';$env:USERPROFILE=$env:HOME;$env:APPDATA=Join-Path $env:HOME 'AppData\Roaming';$env:LOCALAPPDATA=Join-Path $env:HOME 'AppData\Local';$env:TEMP=$TempRoot;$env:TMP=$TempRoot;$env:NO_PROXY='127.0.0.1,localhost';$env:PYTHONNOUSERSITE='1';$env:PYTHONPYCACHEPREFIX=Join-Path $TempRoot 'python-bytecode';$env:HF_HUB_OFFLINE='1';$env:TRANSFORMERS_OFFLINE='1'
}
function New-HexSecret([int]$Bytes=32){$b=New-Object byte[] $Bytes;[Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b);return -join($b|ForEach-Object{$_.ToString('x2')})}
function Write-JsonAtomic([string]$Path,$Value){$t="$Path.tmp";$Value|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $t -Encoding UTF8;Move-Item -LiteralPath $t -Destination $Path -Force}
function Read-Json([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "Required state is missing: $Path"};Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json}
function Test-Payload([string]$Root=$script:ModuleRoot){
 $r=Read-Json (Join-Path $Root 'payload.sha256.json');$expected=@{}
 foreach($e in $r.files){$expected[[string]$e.path]=$true;$p=Join-Path $Root $e.path;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "Missing payload: $($e.path)"};if((Get-Item $p).Length -ne [int64]$e.bytes){throw "Size mismatch: $($e.path)"};if((Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant() -ne $e.sha256){throw "Hash mismatch: $($e.path)"}}
 $mutable=@('config/runtime/','data/','logs/','state/','temp/');$m=Read-Json (Join-Path $Root 'module.json');if($m.mutable_paths){$mutable+=@($m.mutable_paths)}
 Get-ChildItem -LiteralPath $Root -File -Recurse|ForEach-Object{$rel=$_.FullName.Substring($Root.Length+1).Replace('\','/');$skip=($rel -eq 'payload.sha256.json');foreach($prefix in $mutable){$rule=[string]$prefix;if(($rule.EndsWith('/') -and $rel.StartsWith($rule,[StringComparison]::OrdinalIgnoreCase)) -or ($rel.Equals($rule,[StringComparison]::OrdinalIgnoreCase))){$skip=$true}};if(-not $skip -and -not $expected.ContainsKey($rel)){throw "Unexpected static payload file: $rel"}}
 Write-Host "[OK] $($r.module) $($r.version): payload verified"
}
function Get-ProcessRecord([string]$Name){$p=Join-Path $StateRoot "process-$Name.json";if(-not(Test-Path $p)){return $null};try{Read-Json $p}catch{return $null}}
function Get-OwnedProcess([string]$Name){$r=Get-ProcessRecord $Name;if(-not $r){return $null};$p=Get-Process -Id ([int]$r.pid) -ErrorAction SilentlyContinue;if(-not $p){return $null};try{$ticks=$p.StartTime.ToUniversalTime().Ticks}catch{return $null};if([string]$ticks -ne [string]$r.start_ticks){return $null};return $p}
function Quote-Arg([string]$v){if($v -notmatch '[\s"]'){return $v};return '"'+$v.Replace('"','\"')+'"'}
function Start-OwnedProcess([string]$Name,[string]$FilePath,[string[]]$Arguments,[string]$WorkingDirectory){if(Get-OwnedProcess $Name){Write-Host "[OK] $Name already running";return};$line=($Arguments|ForEach-Object{Quote-Arg ([string]$_)}) -join ' ';$p=Start-Process -FilePath $FilePath -ArgumentList $line -WorkingDirectory $WorkingDirectory -RedirectStandardOutput (Join-Path $LogRoot "$Name.stdout.log") -RedirectStandardError (Join-Path $LogRoot "$Name.stderr.log") -WindowStyle Hidden -PassThru;Start-Sleep -Milliseconds 250;if($p.HasExited){throw "$Name exited; see logs"};Write-JsonAtomic (Join-Path $StateRoot "process-$Name.json") ([ordered]@{pid=$p.Id;start_ticks=$p.StartTime.ToUniversalTime().Ticks;executable=$FilePath});Write-Host "[OK] $Name started (PID $($p.Id))"}
function Stop-OwnedProcess([string]$Name){$p=Get-OwnedProcess $Name;if($p){& "$env:SystemRoot\System32\taskkill.exe" /PID $p.Id /T /F|Out-Null;if($LASTEXITCODE -ne 0){throw "Cannot stop $Name"}};Remove-Item (Join-Path $StateRoot "process-$Name.json") -Force -ErrorAction SilentlyContinue;Write-Host "[OK] $Name stopped"}
function Wait-Healthy([string]$Name,[scriptblock]$Probe){Write-Host "[WAIT] $Name readiness (Ctrl+C cancels)";while($true){if(& $Probe){Write-Host "[OK] $Name ready";return};if(-not (Get-OwnedProcess $Name)){throw "$Name exited before readiness"};Start-Sleep 2}}
function Test-Tcp([int]$Port){$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);return $a.AsyncWaitHandle.WaitOne(1500) -and $c.Connected}catch{return $false}finally{$c.Close()}}
function Test-Http([string]$Url,[hashtable]$Headers=@{}){try{Invoke-WebRequest -UseBasicParsing -Uri $Url -Headers $Headers -TimeoutSec 2|Out-Null;return $true}catch{return $false}}
function Write-Connection([hashtable]$Connection){Write-JsonAtomic (Join-Path $StateRoot 'connection.json') $Connection}
function Show-ModuleStatus([string[]]$Names){foreach($n in $Names){if(Get-OwnedProcess $n){Write-Host "$n`tRUNNING"}else{Write-Host "$n`tSTOPPED"}}}
function Set-Installed{$m=Read-Json (Join-Path $ModuleRoot 'module.json');Write-JsonAtomic (Join-Path $StateRoot 'install.ok.json') ([ordered]@{schema=1;module=$m.name;version=$m.version;path=$ModuleRoot;installed_at=[DateTime]::UtcNow.ToString('o')})}
function Begin-Install{Remove-Item (Join-Path $StateRoot 'install.ok.json') -Force -ErrorAction SilentlyContinue}
function Assert-Installed{$m=Read-Json (Join-Path $ModuleRoot 'module.json');$r=Read-Json (Join-Path $StateRoot 'install.ok.json');if($r.module -ne $m.name -or $r.version -ne $m.version){throw "Module must be installed again: $($m.name)"};Test-Payload}
