[CmdletBinding()]param([string]$CommandName='help',[string]$Target='')
. (Join-Path $PSScriptRoot 'lib\runtime.ps1');Initialize-Module $PSScriptRoot
$Runtime=Join-Path $PSScriptRoot 'runtime';$Exe=Join-Path $Runtime 'llama-server.exe';$SettingsPath=Join-Path $ConfigRoot 'settings.json'
function Verify-Payload{Test-Payload;& $Exe --version;if($LASTEXITCODE -ne 0){throw 'llama-server version probe failed'}}
function Install-Llama{Begin-Install;Test-Payload;& $Exe --version;if($LASTEXITCODE -ne 0){throw 'llama-server version probe failed'};New-Item -ItemType Directory -Path (Join-Path $PSScriptRoot 'models\embed'),(Join-Path $PSScriptRoot 'models\llm') -Force|Out-Null;if(-not(Test-Path $SettingsPath)){Write-JsonAtomic $SettingsPath ([ordered]@{embedding_model='models/embed/Qwen3-Embedding-8B-Q4_K_M.gguf';chat_model='models/llm/Vikhr-Nemo-12B-Q4_K_M.gguf';embedding_port=6380;chat_port=6381;embedding_gpu_ingestion=1;embedding_gpu_chat=0;chat_main_gpu=1;chat_tensor_split='0.20,0.80';embedding_context=2048;embedding_batch=512;chat_context=4096;chat_batch=256;chat_parallel=1})};$s=Read-Json $SettingsPath;Write-Connection ([ordered]@{schema=1;module='llama-cpp';embedding_url="http://127.0.0.1:$($s.embedding_port)/v1";chat_url="http://127.0.0.1:$($s.chat_port)/v1";api_key='local-no-auth'});Set-Installed;Write-Host '[OK] llama-cpp installed; copy GGUF files into models/' }
function Model([string]$p){$x=Join-Path $PSScriptRoot $p;if(-not(Test-Path $x -PathType Leaf)){throw "GGUF model missing: $x"};return $x}
function Start-Embedding([string]$mode){$s=Read-Json $SettingsPath;$gpu=if($mode -eq 'ingestion'){$s.embedding_gpu_ingestion}else{$s.embedding_gpu_chat};Start-OwnedProcess 'embedding' $Exe @('--model',(Model $s.embedding_model),'--host','127.0.0.1','--port',$s.embedding_port,'--embedding','--pooling','last','--n-gpu-layers','999','--split-mode','none','--main-gpu',$gpu,'--ctx-size',$s.embedding_context,'--batch-size',$s.embedding_batch,'--no-webui') $Runtime;Wait-Healthy 'embedding' {Test-Http "http://127.0.0.1:$($s.embedding_port)/health"}}
function Start-Chat{$s=Read-Json $SettingsPath;Start-OwnedProcess 'chat' $Exe @('--model',(Model $s.chat_model),'--host','127.0.0.1','--port',$s.chat_port,'--n-gpu-layers','999','--split-mode','layer','--main-gpu',$s.chat_main_gpu,'--tensor-split',$s.chat_tensor_split,'--ctx-size',$s.chat_context,'--batch-size',$s.chat_batch,'--parallel',$s.chat_parallel,'--no-webui') $Runtime;Wait-Healthy 'chat' {Test-Http "http://127.0.0.1:$($s.chat_port)/health"}}
switch($CommandName.ToLowerInvariant()){'install'{Install-Llama}'start'{Assert-Installed;if($Target -eq 'chat'){Start-Chat}elseif($Target -in @('embedding','ingestion','')){if($Target -eq 'ingestion'){Start-Embedding 'ingestion'}else{Start-Embedding 'chat'}}else{throw 'start target: embedding|ingestion|chat'}}'stop'{if($Target){Stop-OwnedProcess $Target}else{Stop-OwnedProcess 'chat';Stop-OwnedProcess 'embedding'}}'status'{Show-ModuleStatus @('embedding','chat')}'devices'{& $Exe --list-devices;exit $LASTEXITCODE}'verify'{Test-Payload;Write-Host '[OK] llama-cpp verified'}'verify-payload'{Verify-Payload}default{Write-Host 'Usage: MODULE.bat install|start [embedding|ingestion|chat]|stop [name]|status|verify|devices';if($CommandName -ne 'help' -and $CommandName){exit 2}}}
