[CmdletBinding()]param([switch]$CheckOnly,[switch]$NonInteractive)
$ErrorActionPreference='Stop';$ModuleRoot=Split-Path -Parent $PSScriptRoot;$Manifest=Get-Content (Join-Path $ModuleRoot 'module.json') -Raw|ConvertFrom-Json;$Root=Split-Path -Parent (Split-Path -Parent $ModuleRoot);$SourceRoot = Join-Path $Root '_src';$CacheRoot = Join-Path $ModuleRoot '_src';$BuildRoot=Join-Path $ModuleRoot '_build';$PayloadRoot=Join-Path $BuildRoot 'payload';$PackageRoot = Join-Path $BuildRoot 'p';$PreparedRoot = Join-Path $Root 'prepared'
function Remove-DirectoryWithRetry([string]$Path,[int]$Attempts=20){for($Attempt=1;$Attempt -le $Attempts;$Attempt++){if(-not(Test-Path -LiteralPath $Path)){return};try{Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop;return}catch{if($Attempt -eq $Attempts){throw};[GC]::Collect();[GC]::WaitForPendingFinalizers();Start-Sleep -Milliseconds 500}}}
function Require-Source([string]$Name,[string]$Url){$Path=Join-Path $SourceRoot $Name;while(-not(Test-Path -LiteralPath $Path -PathType Leaf)){Write-Host "[MISSING] $Name" -ForegroundColor Yellow;Write-Host "[URL]     $Url";Write-Host "[PUT]     $Path";if($NonInteractive -or $CheckOnly){throw "Required source is missing: $Name"};Read-Host 'Put the file at the path above, then press Enter'|Out-Null};return $Path}
function Reset-Directory([string]$Path){Remove-DirectoryWithRetry $Path;New-Item -ItemType Directory -Path $Path -Force|Out-Null}
function Expand-Artifact([string]$Archive,[string]$Destination,[bool]$Strip,[string]$SevenZip){$Stage=Join-Path $BuildRoot ('extract-'+[guid]::NewGuid().ToString('N'));$Content=Join-Path $Stage 'content';New-Item -ItemType Directory -Path $Content -Force|Out-Null;try{if($Archive.EndsWith('.tar.gz',[StringComparison]::OrdinalIgnoreCase)){$Gzip=Join-Path $Stage 'gzip';New-Item -ItemType Directory -Path $Gzip|Out-Null;& $SevenZip x -y "-o$Gzip" $Archive|Out-Null;$Tar=Get-ChildItem $Gzip -Filter '*.tar' -File|Select-Object -First 1;& $SevenZip x -y "-o$Content" $Tar.FullName|Out-Null}else{& $SevenZip x -y "-o$Content" $Archive|Out-Null};if($LASTEXITCODE -ne 0){throw "Cannot expand: $Archive"};$CopyRoot=$Content;if($Strip){$Items=@(Get-ChildItem $Content -Force);if($Items.Count -eq 1 -and $Items[0].PSIsContainer){$CopyRoot=$Items[0].FullName}};New-Item -ItemType Directory -Path $Destination -Force|Out-Null;Copy-Item (Join-Path $CopyRoot '*') $Destination -Recurse -Force}finally{Remove-DirectoryWithRetry $Stage}}
if($ModuleRoot.IndexOfAny([char[]]'!%&^<>|') -ge 0){throw "Unsafe build path: $ModuleRoot"}
New-Item -ItemType Directory -Path $SourceRoot,$CacheRoot,$PreparedRoot -Force|Out-Null
$OnlineRoot=Join-Path $CacheRoot '_online';$OnlineProfile=Join-Path $OnlineRoot 'profile';$OnlineTemp=Join-Path $OnlineRoot 'temp';New-Item -ItemType Directory -Path $OnlineProfile,$OnlineTemp -Force|Out-Null
$env:HOME=$OnlineProfile;$env:USERPROFILE=$OnlineProfile;$env:APPDATA=Join-Path $OnlineProfile 'AppData\Roaming';$env:LOCALAPPDATA=Join-Path $OnlineProfile 'AppData\Local';$env:TEMP=$OnlineTemp;$env:TMP=$OnlineTemp;$env:PIP_CACHE_DIR=Join-Path $OnlineRoot 'pip';$env:UV_CACHE_DIR=Join-Path $OnlineRoot 'uv';$env:PYTHONNOUSERSITE='1'
$SevenZipVersion='26.02';$SevenZipTag='2602';$Bootstrap=Require-Source '7zr.exe' "https://github.com/ip7z/7zip/releases/download/$SevenZipVersion/7zr.exe";$Extra=Require-Source "7z$SevenZipTag-extra.7z" "https://github.com/ip7z/7zip/releases/download/$SevenZipVersion/7z$SevenZipTag-extra.7z";foreach($Artifact in $Manifest.artifacts){Require-Source $Artifact.file $Artifact.url|Out-Null};if($CheckOnly){Write-Host '[OK] digitizer: fixed inputs are present';return}
Reset-Directory $BuildRoot;$ToolRoot=Join-Path $BuildRoot 'tools';New-Item -ItemType Directory -Path $ToolRoot|Out-Null;& $Bootstrap x -y "-o$ToolRoot" $Extra|Out-Null;if($LASTEXITCODE -ne 0){throw 'Cannot bootstrap 7za.exe'};$SevenZip=Join-Path $ToolRoot 'x64\7za.exe';New-Item -ItemType Directory -Path $PayloadRoot|Out-Null
foreach($Artifact in $Manifest.artifacts){$Source=Join-Path $SourceRoot $Artifact.file;$Target=Join-Path $PayloadRoot $Artifact.target;if($Artifact.kind -eq 'file'){New-Item -ItemType Directory -Path (Split-Path -Parent $Target) -Force|Out-Null;Copy-Item $Source $Target -Force}else{Expand-Artifact $Source $Target ([bool]$Artifact.strip_single_root) $SevenZip};if(-not(Test-Path (Join-Path $PayloadRoot $Artifact.key) -PathType Leaf)){throw "Artifact key missing: $($Artifact.key)"}}
& (Join-Path $PSScriptRoot 'build-hook.ps1') -ModuleRoot $ModuleRoot -PayloadRoot $PayloadRoot -SourceRoot $SourceRoot -CacheRoot $CacheRoot -SevenZip $SevenZip
$Packaged=Join-Path $PackageRoot 'modules\digitizer';New-Item -ItemType Directory -Path $Packaged -Force|Out-Null;Copy-Item (Join-Path $PayloadRoot '*') $Packaged -Recurse -Force;foreach($Name in @('MODULE.bat','control.ps1','module.json','README.md')){Copy-Item (Join-Path $ModuleRoot $Name) $Packaged -Force};Copy-Item (Join-Path $ModuleRoot 'lib') (Join-Path $Packaged 'lib') -Recurse -Force
$Archive=Join-Path $PreparedRoot "local-llm-digitizer-$($Manifest.version).7z";if(Test-Path $Archive){Remove-Item $Archive -Force};Push-Location $PackageRoot;try{& $SevenZip a -t7z -mx=7 -ms=on -mmt=on -myv=1900 $Archive 'modules'|Out-Null;if($LASTEXITCODE -ne 0){throw 'Packaging failed'}}finally{Pop-Location};Write-Host "[OK] Prepared: $Archive" -ForegroundColor Green
