[CmdletBinding()]param([string]$ModuleRoot,[string]$PayloadRoot,[string]$SourceRoot,[string]$SevenZip)
$ErrorActionPreference='Stop';$Python=Join-Path $PayloadRoot 'runtime\python\python.exe';$Uv=Join-Path $PayloadRoot 'build\uv\uv.exe';$Rag=Join-Path $PayloadRoot 'ragflow';$Wheelhouse=Join-Path $SourceRoot 'wheelhouse';$Log=Join-Path $SourceRoot 'build-ragflow.log';$Locks=Join-Path $PayloadRoot 'locks'
New-Item -ItemType Directory -Path $Wheelhouse,$Locks -Force|Out-Null;$env:PATH=(Join-Path $PayloadRoot 'build\git\cmd')+';'+(Join-Path $PayloadRoot 'build\git\mingw64\bin')+';'+$env:PATH;$env:PIP_CACHE_DIR=Join-Path $SourceRoot 'cache\pip';$env:UV_CACHE_DIR=Join-Path $SourceRoot 'cache\uv';$env:UV_NO_CONFIG='1';$env:UV_LINK_MODE='copy';$env:PYTHONNOUSERSITE='1'
$Upstream=Join-Path $Locks 'ragflow-0.27.1-upstream.txt';$Windows=Join-Path $Locks 'ragflow-0.27.1-windows.txt'
Push-Location $Rag
try{& $Uv export --frozen --no-group test --no-emit-project --no-emit-package numpy --no-emit-package xgboost --no-emit-package datrie --no-emit-package graspologic --no-emit-package infinity-emb --no-emit-package unclecode-litellm --no-emit-package agentrun-mem0ai --no-header --no-annotate --format requirements-txt --output-file $Upstream *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow lock export failed'}
& $Uv pip compile (Join-Path $Rag 'pyproject.toml') (Join-Path $PSScriptRoot 'ragflow-windows-additions.txt') --python $Python --constraints $Upstream --overrides (Join-Path $PSScriptRoot 'ragflow-windows-overrides.txt') --excludes (Join-Path $PSScriptRoot 'ragflow-windows-excludes.txt') --generate-hashes --no-header --no-annotate --output-file $Windows *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow Windows lock compile failed'}}finally{Pop-Location}
& $Uv pip install --python $Python 'pip==26.2.1' *>>$Log;if($LASTEXITCODE -ne 0){throw 'pip bootstrap failed'}
& $Python -m pip wheel --wheel-dir $Wheelhouse --no-deps --require-hashes --requirement $Windows *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow wheelhouse build failed'}
Copy-Item (Join-Path $PayloadRoot 'vendor\datrie-0.8.3-cp313-cp313-win_amd64.whl') $Wheelhouse -Force
$WheelLock=Join-Path $Wheelhouse 'requirements.lock';& $Python (Join-Path $PSScriptRoot 'prepare_wheelhouse_lock.py') --requirements $Windows --wheelhouse $Wheelhouse --output $WheelLock *>>$Log;if($LASTEXITCODE -ne 0){throw 'Wheelhouse lock failed'}
Copy-Item $WheelLock (Join-Path $Locks 'ragflow-wheelhouse.lock') -Force
& $Uv pip sync --python $Python --no-index --find-links $Wheelhouse --require-hashes $WheelLock *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow wheel sync failed'}
& $Uv pip install --python $Python --no-index --no-deps (Join-Path $Wheelhouse 'datrie-0.8.3-cp313-cp313-win_amd64.whl') *>>$Log;if($LASTEXITCODE -ne 0){throw 'datrie install failed'}
$Vc=Join-Path $PayloadRoot 'vendor\VC_redist.x64.exe';$Stage=Join-Path $PayloadRoot 'vc-stage';New-Item -ItemType Directory -Path "$Stage\parts","$Stage\payload","$Stage\dlls" -Force|Out-Null;& $SevenZip x -y -t# "-o$Stage\parts" $Vc|Out-Null;& $SevenZip x -y "-o$Stage\payload" "$Stage\parts\4.cab"|Out-Null;& $SevenZip x -y "-o$Stage\dlls" "$Stage\payload\a12"|Out-Null;$DllRoot=Join-Path $PayloadRoot 'runtime\vc';New-Item -ItemType Directory -Path $DllRoot -Force|Out-Null;Get-ChildItem "$Stage\dlls\*_amd64"|ForEach-Object{$n=$_.Name.Replace('_amd64','');Copy-Item $_.FullName (Join-Path $DllRoot $n) -Force;Copy-Item $_.FullName (Join-Path (Split-Path $Python) $n) -Force};Remove-Item $Stage -Recurse -Force
Copy-Item (Join-Path $DllRoot 'vcomp140.dll') (Join-Path (Split-Path $Python) 'Lib\site-packages\xgboost\lib\vcomp140.dll') -Force
& $Python (Join-Path $PSScriptRoot 'prepare_ragflow_windows.py') --ragflow-dir $Rag --record (Join-Path $PayloadRoot 'locks\windows-compat.json') *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow compatibility patch failed'}
$Nltk=Join-Path $PayloadRoot 'assets\nltk';& $Python (Join-Path $PSScriptRoot 'prepare_ragflow_assets.py') --ragflow-dir $Rag --nltk-dir $Nltk --record (Join-Path $PayloadRoot 'locks\assets.json') --manual-assets-dir $SourceRoot *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow asset preparation failed'}
& $Python (Join-Path $PSScriptRoot 'sanitize_python_runtime.py') --runtime (Split-Path $Python) --record (Join-Path $PayloadRoot 'locks\python-sanitize.json') *>>$Log;if($LASTEXITCODE -ne 0){throw 'Python sanitization failed'}
& $Uv pip check --python $Python *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow pip check failed'};& $Uv pip freeze --python $Python | Set-Content (Join-Path $Locks 'ragflow-freeze.txt') -Encoding UTF8;if($LASTEXITCODE -ne 0){throw 'RAGFlow freeze failed'};& $Python (Join-Path $PSScriptRoot 'verify_ragflow_runtime.py') --ragflow-dir $Rag *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow runtime verification failed'}
Remove-Item (Join-Path $Rag 'web') -Recurse -Force -ErrorAction SilentlyContinue;Remove-Item (Join-Path $PayloadRoot 'build'),(Join-Path $PayloadRoot 'vendor') -Recurse -Force
& $Python (Join-Path $PSScriptRoot 'audit_portability.py') --root $PayloadRoot --build-root $ModuleRoot --record (Join-Path $Locks 'portability-audit.json') *>>$Log;if($LASTEXITCODE -ne 0){throw 'RAGFlow portability audit failed'}
